// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=github.com/fujiwara402/goa-sample-app/design
// --out=$(GOPATH)/src/github.com/fujiwara402/goa-sample-app
// --version=v1.3.1

package app
